name: Scheduled Report Sender

on:
  schedule:
    - cron: '26 11 * * *'  # Runs daily at 08:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  send-report:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      SECRET: ${{ secrets.SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install psycopg2-binary python-jose

      - name: Run report sender
        run: python scheduled_report_sender.py
